### ISSUE TITLE
Driver installer hangs

### ISSUE THREAD

**Issue by JoshWobbles** [shauleiz/vJoy#16]
Does not complete and just hangs, acts like the KMDF portion has a dialog that is waiting for user response but since it is installed in the background with no UI the dialog is inaccessible and the window just *dings* when attempting to click anything on the installer window (as applications do when there is a child "dialog" window open).

Windows 10 14393

**Comment by shauleiz** [comment]
I get such complaints from time to time. 
Please search my [Forum](http://vjoystick.sourceforge.net/site/forum) for similar cases.
