### ISSUE TITLE
Windows 10 1809 vJoy fails to install

### ISSUE THREAD

**Issue by dvojinov** [shauleiz/vJoy#23]
The installer starts and never finish just hangs there at the very end , looks like the progress bar has reached the end but it never finish the installation . With no option left I force close the installation , in device manager it appears it is installed but it doesn't work it is just there doing nothing .
Once I want to uninstall the vJoy I get message "not able to uninstall" so I have to remove it manually from device manger .

**Comment by RadioMan71** [comment]
Basically have the same issue, I am aware that this is reported earlier, but I do believe this is somehow different.

**Comment by dvojinov** [comment]
this is where it stops and cant finish the installation
![vjoyinstallationfail](https://user-images.githubusercontent.com/38949103/48541142-071bc400-e8cd-11e8-8362-5b466d4cfcd1.png)
ation

**Comment by RadioMan71** [comment]
Maybe this helps…. https://pastebin.com/wjSQcauv

Just look at the last line, I bet that's exactly where the installer keeps hanging.

**Comment by weeryan17** [comment]
I looked in the event viewer and found this gem of an error
`Failed to install driver. Function WdfCollectionCreate failed with status 0xc000009a.`

**Comment by dvojinov** [comment]
W10 getting worse with every update :( this release is pretty messed up

**Comment by RadioMan71** [comment]
Does this mean it needs some other 3rd party driver?  My install is pretty new, pc is just 9 days old now, so I could be missing some files that were in previous windows 10 versions before the updates?

Anyway, I'm glad you're looking into this now, because I keep trying to install this every once in a while and right now I just keep getting the error that vjoy driver is failed to install.

**Comment by shauleiz** [comment]
No, there is no need for another driver. Something in the new W10 release probably revealed an old bug in the driver. No idea what it is.
Frankly, I don't plan to get deep into this issue. vJoy is not supported anymore but since the code is free and open anyone can debug it or rewrite it for W10.
I still monitor this thread so if I can help without spending too much time I will sure do it.

**Comment by weeryan17** [comment]
If someone would like to help me out with fixing this I've created my own [fork](https://github.com/weeryan17/vJoy), and I'd appreciate the help. 
@shauleiz are you still accepting pull requests or when i finish things up should i just deploy it on my own.

**Comment by RadioMan71** [comment]
I know nothing about (virtual) hardware programming and so for my sake and everyone else it's best to stay away from this.  I do use vJoy along with tobii eyetracker to get that to work in euro truck simulator 2 and american truck simulator, there are more games that need vJoy to run, but I left a message on their discord, maybe somebody that reads that can help you :)

**Comment by weeryan17** [comment]
Welp i got the project to build. now i just need to actually fix the original problem.

**Comment by weeryan17** [comment]
Anyone know a free way to create a certificate for the driver? I really don't have money to spend to try and fix this.

**Comment by evilC** [comment]
Nefarius has expressed a willingness to sign versions of vjoy should the need arise. Please drop into his [Discord channel](https://discord.gg/auumq4E)

**Comment by weeryan17** [comment]
So after some digging I know why vjoy is having problems with newer windows 10 versions. as of windows 1809 all drivers are required to be a [Universal windows driver (UWD)](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/getting-started-with-universal-drivers). However only windows 10 support UWDs. so what I think I'm going to do is a complete re-write of vjoy for windows 10 and maintain that and link to the old vjoy for people still on an old operating system because old vjoy will still work for them. I still plan to have it be open source and free so don't worry.

**Comment by shauleiz** [comment]
I'm not sure.
My desktop runs W10 Enterprise 1809 and has vJoy installed. So this is perhaps true for clean installation.
I took a peek at UWD and it seems to me that you will not have to rewrite vJoy but just recompile it and repackage it. Still, a considerable job.

**Comment by dvojinov** [comment]
When my Windows got updated to 1809 evrything was fine, problem started for me after I decided to do a cleen 1809 installation.

**Comment by weeryan17** [comment]
> My desktop runs W10 Enterprise 1809 and has vJoy installed. So this is perhaps true for clean installation.
You i started up a new vm with windows 10 1809 and it worked on a clean install, but i don't think we want to tell people to find/remove all the vjoy files to install it just to have it break later.

> I took a peek at UWD and it seems to me that you will not have to rewrite vJoy but just recompile it and repackage it. Still, a considerable job.
Maybe not but vJoy used a lot of legacy stuff, and it would be a pain to support multiple windows versions due to only windows 10 being the only os to support UWDs.
Also in my opinion it would probably be harder to recompile and re package

**Comment by husketeer** [comment]
Windows 10 version 1809 updated last night to build no 17763.348.
It no longer allows vjoy driver to work, when I go to device manager it says “the device cannot start (Code 10) An unknown item was found in the report descriptor”.
When I try to update the driver it tells me I have the latest version.
This has happened before and after spending an hour with a. Microsoft tech all we could do was restore to a previous build. This obviously only works until the update comes around again. Can you help please as I use this vjoy driver every day. Thanks

**Comment by shauleiz** [comment]
I'm sorry but there's not much I can do.
I no longer work on vJoy and MS has betrayed it's customers by making legacy code incompatible with new versions of OS. Or, by forcing new versions that will render existing code, even legally signed code, worthless.
You might perhaps disable security checks or work in developer mode. Note that this will make your machine vulnerable.

**Comment by husketeer** [comment]
Ok sorry to hear that. So win 10 basically makes vjoy and any applications that use it useless?

**Comment by weeryan17** [comment]
I'm currently working on a vjoy replacement/update for windows 10, but school has been busy for me recently so i haven't been able to work on it much.

**Comment by evilC** [comment]
@weeryan17 See my post above if you need to get it signed

**Comment by husketeer** [comment]
I know a lot of people who would be happy to see this issue sorted. I use Vjoy for Joystick Gremlin and also used it before the rift for the Tobii Eye x tracker

**Comment by Julien51200** [comment]
Hello, I would like to know if the driver has been updated version of windows 18.09?

**Comment by shauleiz** [comment]
Guys,
I stopped developing vJoy.
The code is Open and is documented.
You are welcome to branch and make it Windows 10 (1809) ready

**Comment by eromoe** [comment]
There is a fork ahead of main , I am lacking of tool to build it ,  may someone have a tried ?
https://github.com/weeryan17/vJoy

**Comment by spadino** [comment]
Great! I'll look at it next days!

**Comment by sonicviz** [comment]
Maybe you should see if you can get people to sponsor development of it: https://www.theverge.com/2019/5/23/18637344/github-sponsors-patreon-style-crowdfunding-open-source

**Comment by johnwang16** [comment]
Compiling weeryan17's version seemed to have worked. I used VS 2017 Community edition. I had to disable spectre mitigation in all of the c++ projects in the solution under Properties->Configuration Properties->C/C++->Code Generation.. then for the driver project set the target platform under Properties->Driver Settings->General. Target OS Version = Windows 10 or higher, Target Platform = Universal. After building in VS, then running the buildall.bat (making sure to edit the SET BUILDER line to point to VS 2017), the files in x64/Release/Package actually installed and worked when driver signature enforcement was disabled.

**Comment by qiangqiang101** [comment]
> Compiling weeryan17's version seemed to have worked. I used VS 2017 Community edition. I had to disable spectre mitigation in all of the c++ projects in the solution under Properties->Configuration Properties->C/C++->Code Generation.. then for the driver project set the target platform under Properties->Driver Settings->General. Target OS Version = Windows 10 or higher, Target Platform = Universal. After building in VS, then running the buildall.bat (making sure to edit the SET BUILDER line to point to VS 2017), the files in x64/Release/Package actually installed and worked when driver signature enforcement was disabled.

could you make an unofficial update?

**Comment by johnwang16** [comment]
I don't have a way of signing the driver, which means anyone using it will need to disable driver signing check whenever they want to use it.  It's also weeryan's changes and all I've done is compile it with freely available tools, which anyone can do

**Comment by dmonds** [comment]
Hi @johnwang16,

Thanks for posting this.
I'd like to have a go at this and have just installed VS2017 Community.
When you say "disable driver signing check" ... is that when compiling, building or running?

Sorry, but whilst I've got half a clue, I'm still a noob.

Thx

**Comment by RadioMan71** [comment]
It is when running, so if you install the driver.  About the driver signing, the original programmer of this project @shauleiz may help you with that, but I am just guessing that since @weeryan17 couldn't figure this out, the code he made doesn't really work as it should either, otherwise why spend time on it and leave the project if you finally finished it.

For the people that need this for getting tobii eyetracking to work in Euro Truck Simulator 2 or American Truck Simulator, tobii eyetracking will get native support in the next update of these games, so I don't need this anymore so I leave this for now, thanks to @weeryan17 for having a try on this but my hunch is, it can not be done anymore with the latest windows 10 updates.

**Comment by weeryan17** [comment]
> 
> 
> I am just guessing that since @weeryan17 couldn't figure this out.
I have figured out the issue, but due to school I haven't had much free time to work on this. I plan to get around to it at some point this summer, but I have no clue when as other projects have started taking up my time

**Comment by weeryan17** [comment]
> 
> 
> It is when running, so if you install the driver. About the driver signing, the original programmer of this project @shauleiz may help you with that, but I am just guessing that since @weeryan17 couldn't figure this out, the code he made doesn't really work as it should either, otherwise why spend time on it and leave the project if you finally finished it.

I have someone lined up to sign the driver, It's just not to that point yet.

> 
> For the people that need this for getting tobii eyetracking to work in Euro Truck Simulator 2 or American Truck Simulator, tobii eyetracking will get native support in the next update of these games, so I don't need this anymore so I leave this for now, thanks to @weeryan17 for having a try on this but my hunch is, it can not be done anymore with the latest windows 10 updates.

See my above comment, but if you want to know what the issue getting it working is we talked about it [above](https://github.com/shauleiz/vJoy/issues/23#issuecomment-442684678)

**Comment by johnwang16** [comment]
@dmonds , you can disable driver enforcement by going into advanced startup settings. https://windowsreport.com/driver-signature-enforcement-windows-10/ Since you have to do this every time you boot, it's not really a viable option. There should be a way to self-sign a driver package but I haven't gotten it to work yet.

@RadioMan71 , weeryan's current changes do work. I have it running in a vm using 1903. It's just a matter of compiling it and getting past the signature enforcement.

**Comment by RadioMan71** [comment]
Yeah, I shouldn't have assumed things that I wasn't sure about, good to know it's working now, but like I said I don't really need this anymore, since I needed this in ets2 with tobii eyetracking, but in the next update that will be supported.
Anyway, sorry that I assumed things. [autoassume off]

**Comment by djscott00** [comment]
> > It is when running, so if you install the driver. About the driver signing, the original programmer of this project @shauleiz may help you with that, but I am just guessing that since @weeryan17 couldn't figure this out, the code he made doesn't really work as it should either, otherwise why spend time on it and leave the project if you finally finished it.
> 
> I have someone lined up to sign the driver, It's just not to that point yet.
> 
> > For the people that need this for getting tobii eyetracking to work in Euro Truck Simulator 2 or American Truck Simulator, tobii eyetracking will get native support in the next update of these games, so I don't need this anymore so I leave this for now, thanks to @weeryan17 for having a try on this but my hunch is, it can not be done anymore with the latest windows 10 updates.
> 
> See my above comment, but if you want to know what the issue getting it working is we talked about it [above](https://github.com/shauleiz/vJoy/issues/23#issuecomment-442684678)

Thank you for the work you've put into this thus far. I use Joystick Gremlin which has a critical dependency on vJoy, so I'm definitely invested in the result and am willing to help out in whatever form I can.

While I do a fair amount of development work in c#, it's been a while since I've had to do anything with c++/c, and don't have any previous experience with developing drivers. That aside, I'm totally willing to help out with the costs towards digitally signing the end result.

**Comment by thoklo** [comment]
> I don't have a way of signing the driver, which means anyone using it will need to disable driver signing check whenever they want to use it. It's also weeryan's changes and all I've done is compile it with freely available tools, which anyone can do

**@johnwang16** I would appreciate a copy, knowing I will need to disable driver signing check, until we have a signed version. Since you already have done the compilation and confirmed it worked, would you mind sharing? Even in a dropbox/g-drive etc in case you do not want to publish on github.

Thank you in advance

// Thomas

**Comment by R-T-B** [comment]
Hello all.  I will be aquiring a EV code signing license in the following weeks to produce a proper signed build.  I staged my own changes and a few of @weeryan17's work.  It may take a week or so for a proper signed build.  In the meantime, you may check out my work fork or download a binary installer that works if you are in testsigning mode here:

https://github.com/R-T-B/vJoy/releases/

PS:  If you don't know what testsigning mode is, you can google it.  It leaves a watermark while enabled, but is reversible via a few commands.

**Comment by evilC** [comment]
@R-T-B In case you did not know, Nefarius has expressed a willingness to sign vJoy releases with his cert, so if you are gonna purchase a cert solely to sign vJoy, we can maybe save you quite a lot of money ;)

**Comment by spadino** [comment]
Independently on who will sign this proper vjoy build, I feel the needs for a stable development group. There are too many users and projects which depend on this and definitely it's a sensitive piece of code. There is a way to purchase a certificate as a group?

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by weeryan17** [comment]
Just a heads up to you people my version is NOT ready as i haven't had time to work on it (although i might get it today). Just a quick recap of what we believe to be the problem. In Windows 10 build 1809 microsoft started requiring that drivers be a UWD (Universal Windows Driver) and this caused vjoy to start throwing weird errors and not installing. This is what I believe to be the issue, but i could be wrong as I'm pretty new to driver development. Although I do agree with @spadino I'm currently at a point in my life where my free time is very limited and vjoy isn't at the top of my todo list. I'm glad to maintain the repo, and do some development we really need more people to help out.

Also I've been debating on asking this, but are their people willing to donate to this project as that would give me more reason to work on this in my free time, and if i do get enough donations I could even maybe hire some developers to help me out.

As to not keep taking in this issue I've created a discord server to give more regular updates, and have a better platform to talk with you all. https://discord.gg/uM5aRBX

**Comment by R-T-B** [comment]
I'm working now on the issue of a stable development group on all fronts.  I myself am a capable developer, but I am not currently registered as a business and that is giving me grief.  I also need to be brought up to speed on the code; vJoy is a complex project but I am a fast learner. :)

I am backed in some ways by my employer (who doubles as my mother heh) Kathryn Beehler Reporting, which needs vJoy for something ad obscure as a widely deployed old foot pedal.  I also have my own interest for a game controller I use at home.  I will see about getting my boss / family matriarch to get me an EV code signing certificate to get around the issue of applying as an individual.

Cost is not a concern, and I already have updated the build scripts in prep for this.  Just a waiting game now.

As for hosting, my personal webserver should be adaquate for overseeing a funding and donation tracker.  But I will not accept donations until we have it done right. ;)

-Raymond Beehler
KBR

**Comment by shauleiz** [comment]
This the Shaul.
Have you given a thought about @evilC  proposal? This should save you time (and money). If you wish I will be a able to host it the way I host the current vJoy.
We will have vJoy for Windows 7/8/10 (Until 1809) and vJoy for Windows 10 (1809 and later).
It is also possible to put a link in my site pointing to yours. As you wish.

**Comment by spadino** [comment]
I'm glad to hear from you, Shaul! I think that Nefarious as the signer is a great opportunity. He is know as a very serious and capable kernel mode developer, and I personally support his will to help the project. But, if there the possibility for another certificate, thats can't be bad at all: Nefarious is quite busy...

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by R-T-B** [comment]
> 
> 
> This the Shaul.
> Have you given a thought about @evilC proposal? This should save you time (and money). If you wish I will be a able to host it the way I host the current vJoy.
> We will have vJoy for Windows 7/8/10 (Until 1809) and vJoy for Windows 10 (1809 and later).
> It is also possible to put a link in my site pointing to yours. As you wish.

Either way is fine with me.  My main concern with letting someone else sign it is this:  

> Nefarious is quite busy...

Yes, and for me, that's the rub.  I really do appreciate the offer and it may be good for everyone else here, but we have a business that depends on vJoy (bet you never thought you'd hear that, it's a real odd duck setup) and I can't frankly be expected to wait on someone else to sign a solution when it's needed today/now.  Getting this cert is a cost-analysis situation and signing it vs paying for new hardware in this case is a nobrainer.  If I am estimating correctly from here, it's only around $100 from digicert anyhow,, including mandatory hardware token costs.

https://www.digicert.com/friends/sysdev/

And yes, my motivations are selfish admittedly, but at least I help out while I'm at it, right? ;)

**Comment by ClickerNZ** [comment]
Hi all.

This is, indeed very encouraging!

If I may submit my virtual 2c worth, I do not mind who organizes the cert, however, as a consumer, I'd be keen that who-ever and how-ever this continues, that it be maintained via a (small) group (preferably) who can commit to maintaining vJoy at least semi-continuously.

To that end, what I'd suggest is setting up a Patreon page for people like me who would gladly contribute at the very least, to the ongoing certificate requirement.

Clicker

**Comment by R-T-B** [comment]
> 
> 
> Hi all.
> 
> This is, indeed very encouraging!
> 
> If I may submit my virtual 2c worth, I do not mind who organizes the cert, however, as a consumer, I'd be keen that who-ever and how-ever this continues, that it be maintained via a (small) group (preferably) who can commit to maintaining vJoy at least semi-continuously.
> 
> To that end, what I'd suggest is setting up a Patreon page for people like me who would gladly contribute at the very least, to the ongoing certificate requirement.
> 
> Clicker

I don't disagree.  Whoever ends up signing builds should also ask donations if only to maintain the ongoing certificate cost.  Patreon, whatever, as long as it is something that can be easily managed.  Not only that, I'd go a step further and say that if that individual looses interest this fund should be something that could be transferred to another individual.  It seems to me a simple paypal account for donations would work for that kind of purpose, but am open to other ideas.  I pledge at least that if I stopped working on the project I would forfeit any money collected for "signing purposes" to the next individual willing to sign builds.

We need to keep an active support structure, however that can be maintained.  In my case, if my employer lost interest for whatever reason, I am also a freelance coder who uses vJoy in a gaming setup so I can assure you at least my interest here would still last a while.  So there's that.

**Comment by evilC** [comment]
@R-T-B From what I understand, it is nothing like $100, it is more like $5000 for the cert

**Comment by RTB2011** [comment]
Yep, I did my homework.  If I'm not mistaken, that may be a introductory rate though, so obviously funding is NOT a bad idea.

**Comment by R-T-B** [comment]
Yep, we do our homework here.  I'm still trying to clear up whether that rate is introductory or permanent though...

**Comment by shauleiz** [comment]
You don't need a permanent one. Once you obtain the certificate you have
one year to use it for signing. The signed software is considered signed
for eternity, or until MS decides otherwise.

**Comment by R-T-B** [comment]
Oh I am aware shauleiz, but with Windows 10 being the moving target it's become, doesn't hurt to ask, right?  I mean what if it needs updating again?

I am currently going through the validation process with my employer.  They really don't mess around.  But we should have the cert pretty soon.

**Comment by PhoenixTT** [comment]
> I am currently going through the validation process with my employer. They really don't mess around. But we should have the cert pretty soon.

How is the validation process going?

**Comment by R-T-B** [comment]
> 
> 
> > I am currently going through the validation process with my employer. They really don't mess around. But we should have the cert pretty soon.
> 
> @R-T-B
> How is the validation process going?
> 
> I ask because I don't get the driver signature check in Win 10 disabled. I tried all ways you can find in the internet but only the temporary via troubleshoot reboot is working.

Slowly.  They want our last tax statement and since we have a "tax guy" we are waiting on him to dig it up this week.

But yes, it is moving.

As for your status, have you tried the following in a admin cmd prompt?

bcdedit.exe /set nointegritychecks on

bcdedit /set testsigning on

bcdedit.exe -set loadoptions DISABLE_INTEGRITY_CHECKS

To reverse:

bcdedit.exe /set nointegritychecks off

bcdedit /set testsigning off

bcdedit.exe -set loadoptions ENABLE_INTEGRITY_CHECKS

Yes, it's sort of hacky.  But it works for now until we get something better.


PS: This will leave an ugly watermark on your system in the lower right corner of your desktop.  To disable that I've found this tool works well to remove it.  It is virus free (but may falsely identify as one since it modifies system files):

winaero.com/download.php?view.1794

**Comment by PhoenixTT** [comment]
Thanks for the fast and detailed answer. 

I have tried the bcedit commands, but the device manager still don't load the driver with a signature check error. At the moment I boot always into the troubleshoot boot menu und use F7. In this mode the driver is loaded. Not pretty, but it works. 

So I am also waiting for your "tax guy" ;-)

**Comment by thoklo** [comment]
@PhoenixTT If I understand you right-click the 'Restart' option in Windows to be able to go into troubleshooting and then choose to disable the check, there is a slightly easier way (that works for me at least). **You may know all this already, but I share my view in case it helps someone else.**

In admin command prompt:
BCDEDIT /SET {DEFAULT} BOOTMENUPOLICY LEGACY

That enables the boot menu when pressing F8 repeatedly during boot. You then chose to disable the check in the menu which is easier. 

When you are not using vJoy, you just boot normally and Windows enables the check which is safer on a normal Monday.

The driver stops working (of course) when I boot without disabling the check, but as soon as I do, vJoy works. I do not need to reinstall or anything. All settings are kept. If it does not work, the first place I go to is the Device Manager to see if vJoy has loaded correctly.

If you one day do not want to have the F8 boot menu option, just write in an admin command prompt:
BCDEDIT /SET {DEFAULT} BOOTMENUPOLICY STANDARD

**Comment by PhoenixTT** [comment]
@thoklo Thanks for this explanation and the new bcdedit option. And no, I don't use the manual reboot, I use another bcdedit option which activates the troubleshoot menu every time I reboot. I don't like pressing F8 ;-)

BCDEDIT /SET ADVANCEDOPTIONS TRUE

**Comment by R-T-B** [comment]
Hello all.  Good news bad news time.

The bad news is our business is aparently not up to the lofty "EV Signing" certificate standards.  To clear up what's wrong:  Being a freelance court reporter is a business and taxed as such in the state of Washington.  However, it does not require a business license.  EV Code signing validation requires more than just the court reporter certification uploaded and scanned, they need a bona fide business license.

As such, our business cannot comply, and our signing request was denied.

Being unwilling to open a business to just sign vJoy (besides, I don't WANT to commercialize this, and uh, that's kind of what a business would do), I have turned to my former employer, whom I will not name at this time (though the curious can probably figure it out).  If they express an interest it will become a branded subproject of the organization in question, but that's a small price to pay I think for getting our code signed regularly and reliably.

If they say they it's ok, I will point you users at their email as soon as I have permission to do so (so you can hit them with lots of "I am interested in vJoy!" emails to support the idea).

Wish me luck.

**Comment by PhoenixTT** [comment]
I thank you for your dedication and your decision not to open a business is fully understandable. In the end it is only a joystick game (controller). Whereby I also use it sometimes with my Tobii eye tracker if there is no native support.

Wish you luck and a nice weekend.

**Comment by Haltaar** [comment]
Best of luck @R-T-B your work on this is greaty appreciated.

I have recently broken my SmartPropoPlus/vJoy installation and have had zero luck trying to get vJoy installed again. I recently updated my windows 10 installation to access the new xbox for pc beta. Guess I should have done my homework first, now my RC simulator is unplayable!

I will look into using the unsigned version that you posted. Are there any pitfalls to using windows in the state required that I should know about?

**Comment by R-T-B** [comment]
> 
> 
> Best of luck @R-T-B your work on this is greaty appreciated.
> 
> I have recently broken my SmartPropoPlus/vJoy installation and have had zero luck trying to get vJoy installed again. I recently updated my windows 10 installation to access the new xbox for pc beta. Guess I should have done my homework first, now my RC simulator is unplayable!
> 
> I will look into using the unsigned version that you posted. Are there any pitfalls to using windows in the state required that I should know about?

Just the need for secure boot to be off.  And that security is slightly reduced (malicious drivers could load if asked,  but really, just don't load random drivers other than my vjoy).

As far as function, Windows will continue to work the same as ever.  There'll be a watermark of course, but that can be removed even with the tool I posted with no bad side effect.

**Comment by PhoenixTT** [comment]
@Haltaar The only drawback I experienced in the last week was, that the anti cheat driver of The Divison 2 is not working in the testsign mode. So I have to switch when I want to play. Ohterwise, how R-T-B wrote there is a slightly reduced security. But you would not install software from unknown soruces, would you ;-)

**Comment by DiegoSynth** [comment]
I know that it's hard to go back to a previous project specially when u feel betrayed (in this case by MS.) Back in the day I was developing for XNA, and MS did exactly the same when releasing the last version: gave a damn about people.

That being said, I would like to first thank you Shaul for your excellent work, and then ask you if there would be a possibility of you working back on it for this time, if we all together fund you. I'm pretty sure many people here would accept and help the cause. In any case, it's fine, and I of course understand it.

**Comment by shauleiz** [comment]
Thank you @DiegoSynth  for your comment.
There are two issues here:

1. We need to make minor changes in the driver.
2. It has to be signed with an expensive type of certificate (EV).

The first issue seems to has been resolved by @R-T-B .
Obtaining an EV cert is complicated as only "real" companies can do it and it is relatively expensive. I think @R-T-B is working on it.

**Comment by DiegoSynth** [comment]
I understand now. I cannot see the point of what MS is doing, but I guess it's as usual only related to $$$. Still, it doesn't make any sense at all.
Thank you @shauleiz for your reply, I really hope we can get somewhere.

@R-T-B we are all with you man. Nevertheless, @evilC , what's up with Nefarius offer? Has anyone asked him to please get it signed?

**Comment by spadino** [comment]
Guys, Nefarious is in the discord channel. I'm quite sure he is willing to help... We should stick with a communication channel, to avoid parallel talks and misunderstanding. All you already are in the discord server? https://discord.gg

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by R-T-B** [comment]
No, I am not in discord.  I am largely tapping out as my needs are now filled by a new hardware purchase.

It appears others are following up with a solution on this [issue](https://github.com/shauleiz/vJoy/issues/30) though.  Might want to watch there.

I am glad you are all following up with this. I sadly lost interest after I got stonewalled by nearly everyone I asked in person to help me with a signature and finally just realized I'd have to depend on nefarious on discord; Something unacceptable for our organizations needs (we need an under 6 hour turn around for any future issues, so I advised just dumping the hardware in question for something else. No offense to nefarious but he's just some guy online and I can't ask that kind of demand)

Don't let me deter you though, feel free to fork my code. I really hope you can all get it going for other needs like gaming and such with a valid (even if outdated) signature! Just wanted you to know I'm out, for these purposes. Good luck.

**Comment by DiegoSynth** [comment]
Hello everyone. Just in case, not to miss anything: when we talk about "vJoy" we are including "vGen", right? Because good Shaul not only wrote vJoy, but also gave us xBox emulation with vGen, which is an excellent feature we should preserve.

So when we sign the files, we are including vGen? (say "yes" please :))

**Comment by R-T-B** [comment]
I'm sure if we get things signed in any form we will sign everything in the vjoy installer.  Is it included in that?

**Comment by DiegoSynth** [comment]
As I can see vGen dll is included in the installer (vGenInterface.dll), but not the C# wrapper (vGenInterfaceWrap.dll), which can be downloaded from [here](https://github.com/shauleiz/vGen/releases)
That...is not the optimal situation... but hopefully the wrapper won't need any special black magic to work...
