### ISSUE TITLE
vjoy can't be used in win10 insider preview,version 19h1

### ISSUE THREAD

**Issue by folcol** [shauleiz/vJoy#29]
I try to reinstall,but it does't work and the warning said failed to install

**Comment by ChenLLE** [comment]
I try to reinstall,but it does't work  and the warning said failed to install

**Comment by gylidian** [comment]
I try to reinstall,but it does't work and the warning said failed to install

**Comment by haxnume** [comment]
I try to reinstall,but it does't work and the warning said failed to install

**Comment by myurar1a** [comment]
I try to reinstall,but it does't work and the warning said failed to install

**Comment by gylidian** [comment]
@myurar1a @briankendall 没想到你们也是复读机

**Comment by pingod** [comment]
I try to reinstall,but it does't work and the warning said failed to install
