### ISSUE TITLE
Chrome fails to recognize vJoy on a windows server 2016 VM

### ISSUE THREAD

**Issue by danishS11** [shauleiz/vJoy#31]
Hi, I've installed vJoy on the Windows Server (VM) and configured it, however, chrome browser does not recognize the vJoy device connected. I do see vJoy status as "OK" in the Game Controller panel. It works on the windows 10 machine (real device) however. Is there some special configuration I need to do for it, or does it not support windows server '16?

**Comment by shauleiz** [comment]
vJoy is a normal HID. Only it is virtual.
This means that if you can install an HID (e.g. steering wheel) you can install vJoy.
Perhaps vJoy was not installed successfully. Perhaps your configuration cannot see HIDS.

**Comment by danishS11** [comment]
It does say that it's installed successfully and I can see vJoy in `Device Manager` as well as windows native HIDs. However, chrome does not recognize it no matter what I do.

**Comment by shauleiz** [comment]
Which version of vJoy is it. I see you have installe it on Windows10 1903 -
this requires vJoy 2.1.9 or later.
Then, I do miss something. What Chrome has to do with devices? Can you give
me a link to a site that accesses vJoy or anyother HID?

**Comment by evilC** [comment]
I can confirm that [HTML5 Gamepad Tester](https://html5gamepad.com/) in chrome does indeed not see a vJoy device on a Windows Server 2016 VM.  
[DIView](http://www.leobodnar.com/shop/index.php?main_page=page&id=12) does see it, so Server 2016 does appear to support DirectInput

**Comment by shauleiz** [comment]
Aha, now I see (Well, I can't).
Same problem with FireFox

However: Devices with **buttons** are detected when used by an application (Such as the demo feeder supplied with vJoy).

EDIT:
As a matter of fact, I can see that vJoy is the 10th most popular controller used with this tester.

**Comment by evilC** [comment]
That site works fine with vJoy devices under Win10 - Dunno if it is an inherent issue with 2016, or just VMs . 
I could not tell you how that site reads devices however, I *think* it uses pure HID, not DirectInput, as it can see all the inputs of a DualShock 4, whereas DirectInput cannot

**Comment by danishS11** [comment]
I was testing the vJoy input on gamepadviewer.com and my company website. So @evilC what should be my course of action?

**Comment by evilC** [comment]
From what I can tell, HTML5 has a [Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API), which is what these web pages use.
As the HTML5 tester I linked notes "The Gamepad API is still inconsistent across browsers and OSes"
So I am guessing there is not anything you can do, it simply is not supported on this OS

**Comment by danishS11** [comment]
I see, so I guess I'll spin up a different VM and try on there. Thanks for the help!

**Comment by danishS11** [comment]
@evilC so i created a new Windows 10 VM and tried on there but it still doesn't work on that OS either. To test, I'm using `gamepadviewer.com`

**Comment by evilC** [comment]
It may be an issue with the VM, or could be an issue with the way that site works in a VM. Try DIView in the VM for a more accurate representation of what DirectInput sees. Or, you could be using a version of vJoy that is incompatible with that version of Windows?
