### ISSUE TITLE
vJoy FFB on multiple devices

### ISSUE THREAD

**Issue by Rubikoid** [shauleiz/vJoy#40]
Hello.

While working with FFB i discovered, that sending FFB on any device except first cases NotImplementedException. 
I checked this on the [master version](https://github.com/njz3/vJoy/) of fork.

So, i built driver with traces and checked, what difference between creation effect on first device, and on others, and found, that directx sends HID_GET_FEATURE for virtual joy id `x` with report id=`0x10 * x + reportID`:
`vJoyGetFeature: id=0, xfer=0x13 reportId=0x3` for the the first joy 
`vJoyGetFeature: id=0, xfer=0x23 reportId=0x3` for the the second joy 

But the vjoy accepts only x=0.

So, there are three lines:
https://github.com/njz3/vJoy/blob/master/driver/sys/hid.c#L349
https://github.com/njz3/vJoy/blob/master/driver/sys/hid.c#L334
https://github.com/njz3/vJoy/blob/master/driver/sys/hid.c#L402

I fixed it with `transferPacket->reportId == (HID_ID_X + 0x10 * id)`, and it works  but i'm not sure, that there no more places with the same problem, or this fix can broke something, so just issue, no PR.

okay, maybe i should slap @njz3

**Comment by njz3** [comment]
Hi,
Thanks for catching this bug. It came from my changes related to the new
features (multiple BlockIndex).
The bug may rather come from the if (...) at the lines you pointed. I
should use the local reportId instead of the transferPacket->.
Let me correct this and see if it solves the issue.
Would you mind to test it ?
Benjamin

**Comment by njz3** [comment]
Hi,
I think I fixed it (at least on my computer).
Can you check with the current master at https://github.com/njz3/vJoy/ ?
Benjamin

Le jeu. 30 avr. 2020 à 23:33, Benjamin Maurin <benjamin.maurin@gmail.com> a
écrit :

> Hi,
> Thanks for catching this bug. It came from my changes related to the new
> features (multiple BlockIndex).
> The bug may rather come from the if (...) at the lines you pointed. I
> should use the local reportId instead of the transferPacket->.
> Let me correct this and see if it solves the issue.
> Would you mind to test it ?
> Benjamin
>
>

**Comment by Rubikoid** [comment]
Hi, it's perfect 

So i will merge and test this fix asap, but i'm think this will work. 

By the way, there are no other places, where this problem or the same, can appear? 

Sometimes i catch NotImplemented also on the first controller without any reasons. 

It happens, when `block load report id 2` have `ucTmp[1]=0` 

I'm not familiar with ffb mechanics, and i have no idea, why this happens sometimes.

**Comment by njz3** [comment]
Hi,
You second issue might be related to your ffb application.
For a feature report id 2 (block load report), you should get BlockIndex a
value between 1 and 100 when a new effect is created.
When you get 0, it means your application created too many effects (create
new effects was called more than 100 without) without releasing some of
them (FreeEffect) and you reached the limit.
Benjamin

**Comment by Rubikoid** [comment]
Hi.
Thank you very much, you right. If i sent `StopAll` and `Reset` FFB commands combination before creating effect it, everything fine.

And further... Can you tell me, where i can read about FFB protocol and how it works, how interpreted? I'm writing some proxy between vjoy and physical joy with ffb support, so certain information about protocol is needed...

**Comment by njz3** [comment]
You should have an 'Unload' or a 'Dispose' effect method to release a given
effect.
Il you reset the device, it will clear everything (that works also, but
it's a hammer).

FFB stuff: well do as me and as most of other people. Look to forums and
microsoft msdn, then perform trial and error.
That's the only source of information I had up to now. (if you have money,
maybe you can find some company to develop it).
That's why there are often tons of bugs, nobody really knows it should be
implemented.
Benjamin

**Comment by Rubikoid** [comment]
So, yes, i have these methods, but this issue usually happens after start
my app, so i don't have any effects to dispose.
Maybe ResetVJD should also reset FFB state, i'm not sure.

About forums - i'v spent a lot of time in the google last week, found some
project, forums and a little piece of documentation on msdn, but sometimes
it's difficult to find info about problem or case.


пт, 1 мая 2020 г. в 18:18, njz3 <notifications@github.com>:

> You should have an 'Unload' or a 'Dispose' effect method to release a given
> effect.
> Il you reset the device, it will clear everything (that works also, but
> it's a hammer).
>
> FFB stuff: well do as me and as most of other people. Look to forums and
> microsoft msdn, then perform trial and error.
> That's the only source of information I had up to now. (if you have money,
> maybe you can find some company to develop it).
> That's why there are often tons of bugs, nobody really knows it should be
> implemented.
> Benjamin
>

**Comment by njz3** [comment]
Hi, 
this bug should be fixed now with v2.2.1.1

**Comment by Rubikoid** [comment]
Nice to hear it, thanks!
