### ISSUE TITLE
vJoyInstallLib failure to Install the driver

### ISSUE THREAD

**Issue by b23prodtm** [shauleiz/vJoy#5]
It fails about this block of code. I don"t really understand what UpdateFn does, but the shell looks like to stumble on it anyway.
The OS found an "Unknown Device" afterwards, failed on a file not found, and couldn't install the driver correctly. vJoyInstallLib.cpp : ~line 788
`    if(!UpdateFn(NULL,hwid,InfPath,flags, preboot)) {
	...
	_stprintf_s(prt, MAX_PATH, "cmdUpdate:  UPDATEDRIVERFORPLUGANDPLAYDEVICES(hwid=%s, InfPath=%s) executed OK", hwid, InfPath);
		StatusMessage( NULL, prt,  INFO);
	};
`

**Comment by b23prodtm** [comment]
Please, can someone help out with the following error I get with the installation of the vJoy.inf driver ? You can see below the vJoyInstall.log :+1: 
`+++++++ +++++++ +++++++ +++++++ +++++++ +++++++ +++++++ +++++++ +++++++ +++++++ 
+++++++ +++++++ Sat Aug 20 16:07:48 2016
+++++++ +++++++ OS: 10.0   (x64)
>> main: DeviceHWID --> root\VID_1234&PID_BEAD&REV_0216 ; InfFile --> vJoy.inf
[I]  FindInstalled: Searching for HWID root\VID_1234&PID_BEAD&REV_0216
[I]  FindInstalled: Searching for HWID root\VID_1234&PID_BEAD
[I]  Install: GetFullPathName --> C:\Users\FORMATEUR\Source\Repos\vJoy\x64\Release-Xbox\vJoy.inf 
[I]  Install: hwIdList --> root\VID_1234&PID_BEAD&REV_0216
[I]  Install: SetupDiGetINFClass --> Class Name HIDClass
[I]  Install: SetupDiCreateDeviceInfoList OK
[I]  Install: SetupDiCreateDeviceInfo  OK
[I]  Install: SetupDiSetDeviceRegistryProperty  OK
[I]  Install: SetupDiCallClassInstaller  OK
[I]  Install: Starting cmdUpdate
[I]  cmdUpdate: GetFullPathName --> C:\Users\FORMATEUR\Source\Repos\vJoy\x64\Release-Xbox\vJoy.inf 
[I]  cmdUpdate: Install: Starting cmdUpdate
[I]  cmdUpdate:  File newdev.dll loaded OK
[I]  cmdUpdate:  UPDATEDRIVERFORPLUGANDPLAYDEVICES got OK
[I]  cmdUpdate:  CMP_WaitNoPendingInstallEvents returned WAIT_OBJECT_0
[E]  cmdUpdate:  UPDATEDRIVERFORPLUGANDPLAYDEVICES(hwid=root\VID_1234&PID_BEAD&REV_0216, InfPath=C:\Users\Me\Source\Repos\vJoy\x64\Release-Xbox\vJoy.inf) failed with error: (FILE NOT FOUND)! But the file is there, it's strange.


[I]  cmdUpdate returns code 2
[I]  Install: Finished cmdUpdate
[I]  Install: SetupDiGetDeviceInstanceId (Device Instance Path=ROOT\HIDCLASS\0000) OK
[E]  Install failed`

**Comment by shauleiz** [comment]
This message usually indicates that for some reason file vjoy.inf was not written to your temporary folder or cannot be read from it.
Usually, by selecting another folder (e.g. C:\) will solve the problem.
