### ISSUE TITLE
Default settings change

### ISSUE THREAD

**Issue by SerkaFox** [shauleiz/vJoy#54]
Hello.
I try to change default numbers of buttons from 8 to 16 on Vjoy 1. Where it need to change? And How build setup then? Thank you very much. 
P.S. Are you have discord or else communicate service? 
Best wishes,Serka

**Comment by shauleiz** [comment]
I removed the vJoy site as it was totally infected.
There are several ways to change the default number of buttons.
It has been about 10 years since I wrote the code so it might take me a while to find it. hold tight.

**Comment by SerkaFox** [comment]
> I removed the vJoy site as it was totally infected.
> There are several ways to change the default number of buttons.
> It has been about 10 years since I wrote the code so it might take me a while to find it. hold tight.

I can help with site for make it save and security in good place/hosting,
Anyway I found where this option. but I not sure about that. 
Look - \\vJoy-master\vJoy-master\apps\vJoyConf\vJoyConfig\vJoyConfig.cpp
line 30 : int		g_nButtons = 16; 
I change from 8 to 16, it is right?
But now i have HUGE problem with Build and compile
I install many Gb of all software what system asked and stuck on this problem
`       "X:\PARTYZONE\vJoy-master\vJoy-master\vjoy.sln" (целевой объект по умолчанию) (1) ->
       "X:\PARTYZONE\vJoy-master\vJoy-master\apps\common\vJoyInterfaceStat\vJoyInterfaceStat2012.vcxproj.metaproj" (цел
       евой объект по умолчанию) (11) ->
       "X:\PARTYZONE\vJoy-master\vJoy-master\apps\common\vJoyInterfaceStat\vJoyInterfaceStat2012.vcxproj" (целевой объе
       кт по умолчанию) (15) ->
       (Целевой объект ResourceCompile) ->
         ..\vJoyInterface\gen-versioninfo.h(2): warning RC4005: 'VER_H_' : redefinition [X:\PARTYZONE\vJoy-master\vJoy-
       master\apps\common\vJoyInterfaceStat\vJoyInterfaceStat2012.vcxproj]
         ..\vJoyInterface\gen-versioninfo.h(3): warning RC4005: 'VER_M_' : redefinition [X:\PARTYZONE\vJoy-master\vJoy-
       master\apps\common\vJoyInterfaceStat\vJoyInterfaceStat2012.vcxproj]
         ..\vJoyInterface\gen-versioninfo.h(4): warning RC4005: 'VER_L_' : redefinition [X:\PARTYZONE\vJoy-master\vJoy-
       master\apps\common\vJoyInterfaceStat\vJoyInterfaceStat2012.vcxproj]


       "X:\PARTYZONE\vJoy-master\vJoy-master\vjoy.sln" (целевой объект по умолчанию) (1) ->
       "X:\PARTYZONE\vJoy-master\vJoy-master\apps\FfbMon\FfbMon.vcxproj.metaproj" (целевой объект по умолчанию) (2) ->
       "X:\PARTYZONE\vJoy-master\vJoy-master\apps\common\vJoyInterface\vJoyInterface2012.vcxproj.metaproj" (целевой объ
       ект по умолчанию) (3) ->
       "X:\PARTYZONE\vJoy-master\vJoy-master\apps\common\vJoyInterface\vJoyInterface2012.vcxproj" (целевой объект по ум
       олчанию) (14) ->
         .\gen-versioninfo.h(2): warning RC4005: 'VER_H_' : redefinition [X:\PARTYZONE\vJoy-master\vJoy-master\apps\com
       mon\vJoyInterface\vJoyInterface2012.vcxproj]
         .\gen-versioninfo.h(3): warning RC4005: 'VER_M_' : redefinition [X:\PARTYZONE\vJoy-master\vJoy-master\apps\com
       mon\vJoyInterface\vJoyInterface2012.vcxproj]
         .\gen-versioninfo.h(4): warning RC4005: 'VER_L_' : redefinition [X:\PARTYZONE\vJoy-master\vJoy-master\apps\com
       mon\vJoyInterface\vJoyInterface2012.vcxproj]


       "X:\PARTYZONE\vJoy-master\vJoy-master\vjoy.sln" (целевой объект по умолчанию) (1) ->
       "X:\PARTYZONE\vJoy-master\vJoy-master\apps\vJoyList\vJoyList.vcxproj.metaproj" (целевой объект по умолчанию) (12
       ) ->
       "X:\PARTYZONE\vJoy-master\vJoy-master\apps\vJoyList\vJoyList.vcxproj" (целевой объект по умолчанию) (18) ->
         .\gen-versioninfo.h(2): warning RC4005: 'VER_H_' : redefinition [X:\PARTYZONE\vJoy-master\vJoy-master\apps\vJo
       yList\vJoyList.vcxproj]
         .\gen-versioninfo.h(3): warning RC4005: 'VER_M_' : redefinition [X:\PARTYZONE\vJoy-master\vJoy-master\apps\vJo
       yList\vJoyList.vcxproj]
         .\gen-versioninfo.h(4): warning RC4005: 'VER_L_' : redefinition [X:\PARTYZONE\vJoy-master\vJoy-master\apps\vJo
       yList\vJoyList.vcxproj]


       "X:\PARTYZONE\vJoy-master\vJoy-master\vjoy.sln" (целевой объект по умолчанию) (1) ->
       "X:\PARTYZONE\vJoy-master\vJoy-master\apps\vJoyConf\vJoyConf.vcxproj.metaproj" (целевой объект по умолчанию) (5)
        ->
       "X:\PARTYZONE\vJoy-master\vJoy-master\apps\vJoyConf\vJoyConf.vcxproj" (целевой объект по умолчанию) (23) ->
         .\gen-versioninfo.h(2): warning RC4005: 'VER_H_' : redefinition [X:\PARTYZONE\vJoy-master\vJoy-master\apps\vJo
       yConf\vJoyConf.vcxproj]
         .\gen-versioninfo.h(3): warning RC4005: 'VER_M_' : redefinition [X:\PARTYZONE\vJoy-master\vJoy-master\apps\vJo
       yConf\vJoyConf.vcxproj]
         .\gen-versioninfo.h(4): warning RC4005: 'VER_L_' : redefinition [X:\PARTYZONE\vJoy-master\vJoy-master\apps\vJo
       yConf\vJoyConf.vcxproj]


       "X:\PARTYZONE\vJoy-master\vJoy-master\vjoy.sln" (целевой объект по умолчанию) (1) ->
       "X:\PARTYZONE\vJoy-master\vJoy-master\driver\sys\vJoy.vcxproj.metaproj" (целевой объект по умолчанию) (10) ->
       "X:\PARTYZONE\vJoy-master\vJoy-master\driver\sys\vJoy.vcxproj" (целевой объект по умолчанию) (16) ->
       (Целевой объект ClCompile) ->
         X:\PARTYZONE\vJoy-master\vJoy-master\driver\sys\vjoy.h(46,10): fatal error C1083: Не удается открыть файл вклю
       чение: wdf.h: No such file or directory, [X:\PARTYZONE\vJoy-master\vJoy-master\driver\sys\vJoy.vcxproj]
         X:\PARTYZONE\vJoy-master\vJoy-master\driver\sys\vjoy.h(46,10): fatal error C1083: Не удается открыть файл вклю
       чение: wdf.h: No such file or directory, [X:\PARTYZONE\vJoy-master\vJoy-master\driver\sys\vJoy.vcxproj]
         X:\PARTYZONE\vJoy-master\vJoy-master\driver\sys\vjoy.h(46,10): fatal error C1083: Не удается открыть файл вклю
       чение: wdf.h: No such file or directory, [X:\PARTYZONE\vJoy-master\vJoy-master\driver\sys\vJoy.vcxproj]
         X:\PARTYZONE\vJoy-master\vJoy-master\driver\sys\vjoy.h(46,10): fatal error C1083: Не удается открыть файл вклю
       чение: wdf.h: No such file or directory, [X:\PARTYZONE\vJoy-master\vJoy-master\driver\sys\vJoy.vcxproj]`
       
       WDF.H cant find. But I find this file in folder with WindowsKit, but, when I put this files exactly path to code, i have many more errors with it.
Can you help me? I not a good in it and in code, but I very like your project and want to help you as I can, even some money :)

**Comment by shauleiz** [comment]
Compiling an (old) driver is quite a difficult task. I would not go into it (You will also have to sign the driver). I hope to come with a solution/workaround by tomorrow.

**Comment by SerkaFox** [comment]
> Compiling an (old) driver is quite a difficult task. I would not go into it (You will also have to sign the driver). I hope to come with a solution/workaround by tomorrow.

Ok, ok, I understand that. Thank you for answer, I been shocked when you answer me and I appreciate it. I dont want to disturb you, if you can help me - that will be awesome, you can ask me anything for it. I nervous and wait answer from you asap. Again, thank you.

**Comment by SerkaFox** [comment]
It is me again... Any news?

**Comment by shauleiz** [comment]
Perhaps tonight.
The official way to do it does not work anymore (Perhaps something in W10) so what I plan to do is to create a registry file to accompany the installer. The idea (still to be tested) is that every time the device is activated it is automatically configured from the registry. Should work but I still did not create the registry file. Do you think it is good enough for you?

**Comment by SerkaFox** [comment]
It is AWESOME idea, because we need Virtual Gamepad not always time, only on short period, when we play in game. 
Second what i want to ask - can make some configure files for setup keyboard key for each button? Like, vJoy launch, take configured key from key.conf and all works fine. Because we must use UCR for remapping buttons on vJoy. 
Hmmm, maybe we can talk in discord? 
PartyZone#4995 - me and channel - https://discord.com/invite/Ze2c46n

**Comment by SerkaFox** [comment]
> Perhaps tonight.
> The official way to do it does not work anymore (Perhaps something in W10) so what I plan to do is to create a registry file to accompany the installer. The idea (still to be tested) is that every time the device is activated it is automatically configured from the registry. Should work but I still did not create the registry file. Do you think it is good enough for you?

How can I help, I really want to da that and help you to make it possible. Many people want to play with keyboard, because havent gamepads and you can make this. Like I say, if any help, just ping me in discord or ask some money - it is ok too, I understand your time and your skill for this work.
Repeat Discord - PartyZone#4995 - me and channel - https://discord.com/invite/Ze2c46n

**Comment by shauleiz** [comment]
Unfortunately, much of my work regarding initialization is unusable anymore. Either disabled by later developers or something that I wrote does not function in W10. 
However, I think I have a workaround. Tested for vJoy 2.1.9.1 on Windows 10.

I attach a  file [Dev01Btn16Ver2191.txt](https://github.com/shauleiz/vJoy/files/7159993/Dev01Btn16Ver2191.txt). Please rename it's extension to REG.
It should be incorporated into the target machine before installing vJoy.
Please test it and see if it useful for you.

**Comment by SerkaFox** [comment]
> Unfortunately, much of my work regarding initialization is unusable anymore. Either disabled by later developers or something that I wrote does not function in W10.
> However, I think I have a workaround. Tested for vJoy 2.1.9.1 on Windows 10.
> 
> I attach a file [Dev01Btn16Ver2191.txt](https://github.com/shauleiz/vJoy/files/7159993/Dev01Btn16Ver2191.txt). Please rename it's extension to REG.
> It should be incorporated into the target machine before installing vJoy.
> Please test it and see if it useful for you.

Woah, YOU ARE AWESOME!!! Yes, it is WORK!!! I add reg, then install vJoy and default numbers of buttons - 16. COOL!!!
Sad hear about other features, but vJoy a LIFE and still work perfectly. Now I need combinate and make some script or something to split together Reg file then install file. I think I can do that. 
Btw, are you think about make static buttons remap on default? Like Button number 1 - key "A", button number 2 - key "S" and etc. It is possible?

**Comment by SerkaFox** [comment]
And i try to add this reg code by AutoHotKey app, but confused about it. Can I write by one line first parameter?

**Comment by shauleiz** [comment]
> Now I need combinate and make some script or something to split together Reg file then install file. I think I can do that.

The installer is part of the project in github. You can either reverse-engineer it and write your own installer **or** fork and fix it. Should not be to difficult. 

>  are you think about make static buttons remap on default? Like Button number 1 - key "A", button number 2 - key "S" and etc. It is possible?

The mission of vJoy was to create a virtual **standard** HID device. Mapping is another task.  It was taken on by quite a few other writers. I remember that there were a few excellent mapping apps.
On the other hand, you can write your own **feeder** that does just that.  There is a demo feeder in the package. if you are a reasonable C/C++/C# programmer you will write this feeder within a day at most.
Good luck.
