### ISSUE TITLE
How to check why joy cannot config wheel

### ISSUE THREAD

**Issue by hoantv** [shauleiz/vJoy#56]
Hello,  
im creator of VNM wheelbase firmware. Some users told to me my firmware cannot work with Vjoy. I just tested and saw that can not map with vjoy. It hasnt log so i didnt have any clue to troubleshoot. any requirement for a ffb device to map to jvoy.
Would you help me to add log to vjoy config to see what is the cause?
thank you,

**Comment by shauleiz** [comment]
I do not develop vJoy anymore. Please see if any of the forked project can help.
