### ISSUE TITLE
Can not build the project on win10/11 with vs2019

### ISSUE THREAD

**Issue by Amir-ht** [shauleiz/vJoy#69]
Hi 

I have just pulled the repository and ran the "vjoy.sln" file with vs2019 after compile the project i get this error from "hidkmdf.c and vjoy.h"
files in their project.
 
Error -> C1083	Cannot open include file: 'wdm.h': No such file or directory	hidkmdf	 
Error -> C1083	Cannot open include file: 'Ntddk.h': No such file or directory  vjoy

<img width="1238" alt="error" src="https://github.com/shauleiz/vJoy/assets/142354990/6d632d70-db9a-4f65-a235-ef7e527f67a3">

for the more information I have already installed all version of WDK and all dependencies that mentioned in the git note.

**Comment by njz3** [comment]
You probably have a bad installation of the WDK or SDK.
Just tried on VS2022 with latest WDK and SDK and was able to compile.
